name: "Build the project"
description: "This action builds the project."

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6

    - name: Setup Node.js environment
      uses: actions/setup-node@e33196f7422957bea03ed53f6fbb155025ffc7b8 # v3.7.0
      with:
        node-version-file: '.node-version'

    - name: Install dependencies
      run: yarn install --frozen-lockfile
      shell: bash

    - name: Build the project
      run: |
        yarn generate
        yarn build
      shell: bash
