version: "2.2"

services:
  hub-spid-login:
    build:
      context: ../../../
      dockerfile: Dockerfile
    environment:
      - NODE_TLS_REJECT_UNAUTHORIZED=0
    env_file:
      - env.scenario
    depends_on:
      redis-cluster:
        condition: service_healthy
      spid-saml-check:
        condition: service_started
    expose:
      - ${SERVER_PORT}
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    command: ["yarn", "start"]
    volumes:
      - "./res/certs:/usr/src/app/certs:ro"
      # - "../../../:/usr/src/app/"
    networks:
      - spid-net

  spid-saml-check:
    image: ghcr.io/pagopa/spid-saml-check:v.1.8.3-snapshot@sha256:6349005e929962ab612feedb228130bce42b1f3cffb7bb0434e716bfac243638
    restart: unless-stopped
    environment:
      - NODE_TLS_REJECT_UNAUTHORIZED=0
    ports:
      - ${SPID_DEMO_IDP_PORT}:${SPID_DEMO_IDP_PORT}
    volumes:
      - "./res/spidsamlcheck-conf:/spid-saml-check/spid-validator/config"
      - "./res/hsl-conf:/data/bootstrap"
    networks:
      - spid-net

  #
  #                   __ __            __             __ 
  #   .----.-----.--|  |__.-----.----|  .--.--.-----|  |_.-----.----.
  #  |   _|  -__|  _  |  |__ --|  __|  |  |  |__ --|   _|  -__|   _|
  # |__| |_____|_____|__|_____|____|__|_____|_____|____|_____|__|
  #
  #
  redis-node-0:
    image: docker.io/bitnami/redis-cluster:6.2@sha256:d973a2aa8b6688190ca4e4544b2ff859ef1e9f8081518558270df34e23ff1df7
    networks:
      - spid-net
    ports:
      - 6380:6379
    volumes:
      - redis-node-0-data:/bitnami/redis/data
    environment:
      - 'REDIS_NODES=redis-cluster redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4'
      - 'ALLOW_EMPTY_PASSWORD=yes'

  redis-node-1:
    image: docker.io/bitnami/redis-cluster:6.2@sha256:d973a2aa8b6688190ca4e4544b2ff859ef1e9f8081518558270df34e23ff1df7
    networks:
      - spid-net
    ports:
      - 6381:6379
    volumes:
      - redis-node-1-data:/bitnami/redis/data
    environment:
      - 'REDIS_NODES=redis-cluster redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4'
      - 'ALLOW_EMPTY_PASSWORD=yes'

  redis-node-2:
    image: docker.io/bitnami/redis-cluster:6.2@sha256:d973a2aa8b6688190ca4e4544b2ff859ef1e9f8081518558270df34e23ff1df7
    networks:
      - spid-net
    ports:
      - 6382:6379
    volumes:
      - redis-node-2-data:/bitnami/redis/data
    environment:
      - 'REDIS_NODES=redis-cluster redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4'
      - 'ALLOW_EMPTY_PASSWORD=yes'

  redis-node-3:
    image: docker.io/bitnami/redis-cluster:6.2@sha256:d973a2aa8b6688190ca4e4544b2ff859ef1e9f8081518558270df34e23ff1df7
    networks:
      - spid-net
    ports:
      - 6383:6379
    volumes:
      - redis-node-3-data:/bitnami/redis/data
    environment:
      - 'REDIS_NODES=redis-cluster redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4'
      - 'ALLOW_EMPTY_PASSWORD=yes'

  redis-node-4:
    image: docker.io/bitnami/redis-cluster:6.2@sha256:d973a2aa8b6688190ca4e4544b2ff859ef1e9f8081518558270df34e23ff1df7
    networks:
      - spid-net
    ports:
      - 6384:6379
    volumes:
      - redis-node-4-data:/bitnami/redis/data
    environment:
      - 'REDIS_NODES=redis-cluster redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4'
      - 'ALLOW_EMPTY_PASSWORD=yes'

  redis-cluster:
    image: docker.io/bitnami/redis-cluster:6.2@sha256:d973a2aa8b6688190ca4e4544b2ff859ef1e9f8081518558270df34e23ff1df7
    networks:
      - spid-net
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD", "redis-cli", "-c", "--raw", "incr", "foo"]
      interval: 1s
      timeout: 3s
      retries: 5
    volumes:
      - redis-cluster-data:/bitnami/redis/data
    depends_on:
      - redis-node-0
      - redis-node-1
      - redis-node-2
      - redis-node-3 
      - redis-node-4
    environment:
      - 'ALLOW_EMPTY_PASSWORD=yes'
      - 'REDIS_NODES=redis-cluster redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4'
      - 'REDIS_CLUSTER_CREATOR=yes'
  #
  #
  #
  #

networks:
  spid-net:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450

volumes:
  redis-node-0-data:
  redis-node-1-data:
  redis-node-2-data:
  redis-node-3-data:
  redis-node-4-data:
  redis-cluster-data:
